name: Merge workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run build script
        run: ./.github/scripts/firebase_broken.sh
        shell: bash
      - name: Build project
        run: npm run build -- --configuration production
